// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbdicuwlkjsitfydrplr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxiZGljdXdsa2pzaXRmeWRycGxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MjM2MDMsImV4cCI6MjA3MjE5OTYwM30.1v3LHShZ_lunNVkw1IlLahUCAAqVghI7s4veLrvwPrg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});